name: file_copy
description: Copy a file to your phone.
version: 0.0.1
publish_to: none 

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # flutter_lints: ^1.0.0

